### ISSUE TITLE
以前的版本是不是没有Nodeid这个参数

### ISSUE THREAD

**Issue by ck-chenkang** [advwacloud/WISEPaaS.DataHub.Edge.DotNet.SDK.Sample#1]

**Comment by coolgo0811** [comment]
您好:
      因為以前SCADA的版本是使用ScadaId, 後來更名成DataHub後ScadaId也同時更名成NodeId, 不過邏輯都是一樣的, 希望這樣有回答到您的問題.

**Comment by ck-chenkang** [comment]
好的，谢谢了，有没有1.0.11Nuget套件的下载地址，我这边有个网址上的最新版是1.0.7

**Comment by coolgo0811** [comment]
可以參考線上文件:
https://docs.wise-paas.advantech.com/zh-CN/Guides_and_API_References/Data_Acquisition/DataHub/cs_Edge_SDK_Manual
裡面有nuget package連結, 或是透過以下連結獲取
https://www.nuget.org/packages/WISEPaaS.DataHub.Edge.DotNet.SDK
也可以直接在virtual studio nuget manager直接搜尋 WISEPaaS.DataHub.Edge.DotNet.SDK

**Comment by ck-chenkang** [comment]
谢谢，谢谢
